const hotels = [
  {
    name: 'Hotel California',
    location: 'Paris, France',
    image: 'hotel-california.jpg',
    price: 300,
    currency: 'EUR',
    rating: 4.7,
    reviews: 157,
  },
  {
    name: 'Grand Hotel',
    location: 'Rome, Italy',
    image: 'grand-hotel.jpg',
    price: 250,
    currency: 'EUR',
    rating: 4.5,
    reviews: 320,
  },
  {
    name: 'Majestic Resort',
    location: 'Phuket, Thailand',
    image: 'majestic-resort.jpg',
    price: 150,
    currency: 'USD',
    rating: 4.2,
    reviews: 102,
  },
  {
    name: 'The Ritz London',
    location: 'London, UK',
    image: 'the-ritz-london.jpg',
    price: 450,
    currency: 'GBP',
    rating: 4.8,
    reviews: 462,
  },
  {
    name: 'Electra Palace Athens',
    location: 'Athens, Greece',
    image: 'electra-palace-athens.jpg',
    price: 200,
    currency: 'EUR',
    rating: 4.5,
    reviews: 212,
  },
  {
    name: 'The Tokyo Station Hotel',
    location: 'Tokyo, Japan',
    image: 'tokyo-station-hotel.jpg',
    price: 40000,
    currency: 'JPY',
    rating: 4.9,
    reviews: 634,
  },
  {
    name: 'Four Seasons Hotel Cairo at Nile Plaza',
    location: 'Cairo, Egypt',
    image: 'four-seasons-hotel-cairo-at-nile-plaza.jpg',
    price: 300,
    currency: 'USD',
    rating: 4.7,
    reviews: 314,
  },
  {
    name: 'Raffles Hotel Le Royal',
    location: 'Phnom Penh, Cambodia',
    image: 'raffles-hotel-le-royal-phnom-penh.jpg',
    price: 400,
    currency: 'USD',
    rating: 4.8,
    reviews: 300,
  },
];

export default hotels;
