export default [
    {
        img: "/images/Mexico.jpg",
        rating: "4.32",
        n_rates: "(147)",
        title: "Hotel Zone",
        price: "$70",
        distance: "0.2",
        location: "Cancun, Mexico",
        text: "5389",
    },
    {
        img: "/images/Iceland.jpg",
        rating: "4.71",
        n_rates: "(189)",
        title: "Alp House",
        price: "$297",
        distance: "1.0",
        location: "Nesjavellir, Iceland",
        text: "401",
    },
    {
        img: "/images/Crete.jpg",
        rating: "4.26",
        n_rates: "(205)",
        title: "Beach House",
        price: "$210",
        distance: "0.8",
        location: "Crete, Greece",
        text: "296",
    },
    {
        img: "/images/Cape-Town-South-Africa.jpg",
        rating: "4.58",
        n_rates: "(211)",
        title: "Apartment",
        price: "$170",
        distance: "3.2",
        location: "Cape Town, South Africa",
        text: "173",
    },
]